site_name: FastRTC
site_url: https://sitename.example
repo_name: fastrtc
repo_url: https://github.com/freddyaboulton/gradio-webrtc
theme:
  name: material
  palette:
    scheme: fastrtc-dark
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
  logo: fastrtc_logo.png
  favicon: fastrtc_logo.png
extra_css:
    - stylesheets/extra.css
nav:
  - Home: index.md
  - User Guide:
    - Core Concepts: userguide/streams.md
    - Audio Streaming: userguide/audio.md
    - Video Streaming: userguide/video.md
    - Audio-Video Streaming: userguide/audio-video.md
    - Gradio: userguide/gradio.md
  - Cookbook: cookbook.md
  - Deployment: deployment.md
  - Advanced Configuration: advanced-configuration.md
  - Utils: utils.md
  - Frequently Asked Questions: faq.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details